[template]
src = "remakerings.conf.tmpl"
dest = "/etc/services.d/swift/remakerings"
keys = [
  "/RINGS/"
]

# These are the commands that will be used to check whether the rendered config is
# valid and to reload the actual service once the new config is in place
# check_cmd = "/usr/sbin/nginx -t"
# reload_cmd = "/usr/sbin/service nginx reload"
